version: "3.8"
services:
  dcs-postgres:
    image: postgres:15.3-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
